ERROR [2021-01-10T15:27:30,510] : [http-nio-8080-exec-7] : ResponseExceptionHandler: manejarModeloException(): ExceptionResponseCustom [httpStatus=404 NOT_FOUND, message=ID NO ENCONTRADO 12313, code=SOAINT001, backendMesage=Recurso no encontrado., fecha=2021-01-10T15:27:30.510]
ERROR [2021-01-10T18:39:55,058] : [http-nio-8080-exec-3] : ResponseExceptionHandler: runtimeException(): ExceptionResponseCustom [httpStatus=500 INTERNAL_SERVER_ERROR, message=null, code=, backendMesage=, fecha=2021-01-10T18:39:55.058]
ERROR [2021-01-10T18:40:07,528] : [http-nio-8080-exec-4] : ResponseExceptionHandler: runtimeException(): ExceptionResponseCustom [httpStatus=500 INTERNAL_SERVER_ERROR, message=null, code=, backendMesage=, fecha=2021-01-10T18:40:07.528]
ERROR [2021-01-10T18:40:12,700] : [http-nio-8080-exec-6] : ResponseExceptionHandler: manejarModeloException(): ExceptionResponseCustom [httpStatus=404 NOT_FOUND, message=ID NO ENCONTRADO 1876876, code=SOAINT001, backendMesage=Recurso no encontrado., fecha=2021-01-10T18:40:12.700]
ERROR [2021-01-10T18:40:35,535] : [http-nio-8080-exec-8] : ResponseExceptionHandler: MethodArgumentTypeMismatchException(): ExceptionResponseCustom [httpStatus=500 INTERNAL_SERVER_ERROR, message=Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "AKSJDHASKD", code=SOAINT002, backendMesage=Error en los argumentos(datos, parametros)., fecha=2021-01-10T18:40:35.535]
